version: "3.8"

services:
  backend:
    build:
      args:
        ENV: dev
    volumes:
      - ./tox.ini:/app/tox.ini
      - ./reports:/app/reports
    entrypoint: >
      bash -c "cd /app && python3 -m pytest
      --junitxml=/app/reports/report.xml
      --cov="backend" --cov-config=tox.ini
      --cov-branch --cov-fail-under=0
      --cov-report=xml /app/backend"
