version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: backend
    volumes:
      - .:/app
    hostname: backend
    ports:
      - 5000:5000
