version: "3.8"

services:
  kmk-backend:
    build:
      context: .
      dockerfile: ./kmk-backend/Dockerfile
    container_name: kmk-backend
    volumes:
      - .:/app
    hostname: kmk-backend
    ports:
      - 5000:5000
