name: CI
on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: "3.9"

      - name: Lint code with flake8
        run: |
          export target=$GITHUB_BASE_REF && \
          export files=$(git diff --name-only --relative origin/${target} -- '*.py') && \
          echo "$files"

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          scripts/run_tests.sh
