name: CI
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel

      - name: Install dependencies
        run: |
          pipenv install --deploy --dev

      - name: Run tests
        run: |
          bash -c "python -m pytest
          --cov="backend" --cov-config=tox.ini
          --cov-branch --cov-fail-under=0
          --cov-report term-missing /backend"
